random:
    # What sound to play when the "spectral" attack is used.
    spectral sound: ENTITY_VILLAGER_YES
    # Whether to enforce drops even when 'keepInventory' or similar are enabled.
    workaround drops: false
    # How fast to try to shoot things (EG arrows).
    shoot speed minimum: 20
    # How many calculation cycles before an NPC will give up on a good target.
    clever ticks: 10
    # Whether to workaround potential issues with entity-follow pathfinding.
    workaround entity chase pathfinder: false
    # Whether to prevent players from damaging NPCs that are guarding them.
    no guard damage: true
    # The maximum health value for any given Sentinel NPC.
    max health: 2000
    # Whether to permit death messages to show for Sentinel NPC deaths.
    death messages: true
    # Whether skull attack is allowed.
    skull allowed: true
    # Whether to block some Bukkit events related to Sentinel NPCs from ever running. Will cause weirdness with basic functionality.
    # Recommended to use this alongside other workaround options.
    workaround bukkit events: false
    # How long (in ticks) NPCs should run away for (when hit or told to avoid threats).
    run away time: 1200
    # Whether to ignore targets that are invisible.
    ignore invisible targets: true
    # Distances used for NPCs following their guarded player
    guard follow distance:
        # Minimum distance before choosing a new point (relative to guarded player)
        minimum: 7
        # Maximum possible distance of point to choose (relative to the guarded player)
        selection range: 4
    # Whether NPCs are protected from damage by ignore targets.
    protected: false
    # Whether to force damage through (particularly for ranged attacks).
    enforce damage: false
    # Whether to use 'workaround' mode of fist damage.
    workaround damage: false
# Do not touch! (Unless you know what you're doing!)
config version: 8
#----------- Important! -----------
# Your configuration file was outdated.
# It has been automatically updated.
# You may notice some duplicated comments or other minor inconsistencies,
# if these annoy you, you may remove the duplicate comments OR
# delete the config file to allow it to regenerate.
#
# The below value is how many times automatic updates have been applied
# since you last cleaned this file.
# ----------- End Important! -----------
times_changed: 1
# Sentinel plugin configuration file
# Default settings for a new NPC
sentinel defaults:
    # Whether enemy mobs killed by this NPC should drop items.
    enemy drops: false
    # How much damage to do. -1 for calculated values.
    damage: -1
    # Attack rate, in ticks.
    attack rate: 30
    # Whether 'close quarters' NPCs should chase targets.
    close chase target: true
    # Whether this NPC is invincible.
    invincible: false
    # How far the NPC can reach.
    reach: 3
    # How much health to have.
    health: 20
    # Accuracy offset, 0 means perfectly accurate, 5 means pretty inaccurate.
    accuracy: 0
    # Whether 'ranged attack' NPCs should chase targets.
    ranged chase target: false
    # What movement (chase) speed should be used, as a multiple of the default speed.
    speed: 1.5
    # Default respawn time, in ticks.
    respawn time: 100
    # Whether this NPC will avoid damaging non-targets.
    safe shot: true
    # Whether the NPC should run away when attacked.
    runaway: false
    # Whether to automatically switch to the most appropriate available weapon. (Bow at range, or sword up close).
    autoswitch: false
    # How much armor to have (percentage). -1 for calculated values.
    armor: -1
    # Whether this NPC needs ammo to fight with.
    needs ammo: false
    # "Realistic" logic, don't attack targets we can't see, if enabled.
    realistic: false
    # How far the NPC should stay away from threats (listed by 'addavoid' command).
    avoid range: 10
    # How long to target temporary enemies for, in ticks. 0 means never-forget.
    enemy target time: 0
    # Heal rate, in ticks.
    heal rate: 30
    # Whether this NPC fights back.
    fightback: true
# How fast to recalculate, in ticks.
update rate: 10
