# ----------------------------------- #
#   LoreAttributesRecoded // Worlfy   #
# ----------------------------------- #

lore:
  health:
    enabled: false
    base-health: 20
    keyword: health
  regen:
    keyword: regen
  damage:
    keyword: damage
  dodge:
    keyword: evasion
  critical-chance:
    keyword: critical chance
  critical-damage:
    keyword: critical damage
  life-steal:
    keyword: life steal
  xplevel:
    keyword: xp level
  armor:
    keyword: armor
  restriction:
    keyword: type
    display-message: false
    message: You can't use the %itemname%
  smite:
    keyword: smite
  bane:
    keyword: bane
  defense:
    keyword: absorption
  unbreakable:
    keyword: unbreakable
