# For more information, check out the plugin manual or join us on Discord:
# http://www.mythicmobs.net
#
Configuration:
  Version: 4.6
  General:
    AllowMetrics: true
    CheckForUpdates: true
    CompatibilityMode: true
    DebugLevel: 0
    ErrorLogging: true
    Language: enUS
    UseVolatileFeatures: true
  Clock:
    ClockInterval: 5
    SaveInterval: 5
    SpawnsInterval: 2
    ScannerInterval: 10
    CleanupInterval: 600
  Components:
    CustomSpawners: true
    RandomSpawning: true
  Mobs:
    DespawnByDefault: true
    EnableAIModifiers: true
    EnableTimerSkills: true
    EnableThreatTables: true
    EnablePlayerFactions: true
    EnableLegacySkills: true
    KillMessagePrefix: ''
    PreventOtherDropsByDefault: false
    ShowHealth:
      Radius: 25
      Format: <mob.name> - <mob.php> (<mob.hp> / <mob.mhp>)
    Scaling:
      Esparcraft:
        Enabled: true
        PerBlocksFromSpawn: 6
    DefaultLevelModifiers:
      Health: 2
      Armor: 0
      Damage: 0
      KnockbackResistance: 0
      Power: 1
  RandomSpawning:
    DisableVanillaSpawns: false
    GenerateSpawnPoints: false
    MaxMobsPerChunk: 10
    SpawnRadiusPerPlayer: 25
    SpawnRadiusPerPlayerY: 32
    DespawnLazyRandomMobs: true
    MaxGenerationTime: 20
    PointsPerSecond:
      Land: 10
      Air: 0
      Sea: 2
      Lava: 0
      Ground: 0
  Compatibility:
    Heroes:
      Enabled: false
    McMMO:
      Enabled: false
      ShowXPMessage: true
      XPMessageFormat: You receive <drops.mcmmo> experience for slaying <mob.name>
    SkillAPI:
      Enabled: true
      ShowXPMessage: true
      XPMessageFormat: '&6<drops.xp>&2 de experiencia'
    Vault:
      Enabled: true
      ShowMoneyMessage: true
      MoneyMessageFormat: '&6Consumiste &5<drops.money> Almakos'
